Repository sen-newface/msm-yeahcheese, pull requests merged in 2020-05, with the labels that each got.

#63 template.blade.phpのエラー修正
  yeahcheese/resources/views/layouts/template.blade.php
Labels: レビュー中

#61 [イベント一覧-機能]イベント全取得
  yeahcheese/app/Event.php
  yeahcheese/app/Http/Controllers/EventController.php
  yeahcheese/app/Picture.php
  yeahcheese/app/User.php
  yeahcheese/database/seeds/DatabaseSeeder.php
  yeahcheese/database/seeds/EventsTableSeeder.php
  yeahcheese/database/seeds/PicturesTableSeeder.php
  yeahcheese/database/seeds/UsersTableSeeder.php
  yeahcheese/resources/views/events_list.blade.php
Labels: レビュー中

#62 イベントを表示
  yeahcheese/app/Http/Controllers/EventController.php
  yeahcheese/resources/views/event.blade.php
Labels: レビュー中

#69 [イベント一覧-機能]ログインチェック
  yeahcheese/app/Http/Controllers/Auth/LoginController.php
  yeahcheese/app/Http/Controllers/EventController.php
  yeahcheese/resources/views/events_list.blade.php
Labels: なるはや, レビュー中

#71 homeとlogoutのリンク追加
  yeahcheese/resources/views/layouts/template.blade.php
Labels: レビュー中

#67 Feature/create/search event
  yeahcheese/app/Http/Controllers/EventController.php
  yeahcheese/resources/views/event.blade.php
  yeahcheese/resources/views/search.blade.php
  yeahcheese/routes/web.php
Labels: なるはや, レビュー中

#73 イベントのバリデーション
  yeahcheese/app/Event.php
  yeahcheese/app/Http/Controllers/EventController.php
  yeahcheese/resources/views/event_create.blade.php
Labels: レビュー中

#77 [イベント一覧-機能]掲載期間外のイベントは見れないようにする
  yeahcheese/app/Http/Controllers/EventController.php
  yeahcheese/resources/views/events_list.blade.php
Labels: レビュー中

#78 Fix/search event
  yeahcheese/app/Http/Controllers/EventController.php
  yeahcheese/resources/views/event.blade.php
Labels: なるはや

#83 [fix-共用テンプレート]テンプレートの修正
  yeahcheese/resources/views/layouts/template.blade.php
Labels: レビュー中

#97 [refactor-全体]middlewareの適用範囲をグループ化する
  yeahcheese/routes/web.php
Labels: レビュー中

#100 APIのコントローラーを作成してメソッドを追加
  yeahcheese/app/Http/Controllers/Api/EventController.php
  yeahcheese/app/Http/Controllers/Api/PictureController.php
Labels: なるはや, レビュー中

#99 API用のルーティング情報を記述
  yeahcheese/routes/api.php
Labels: なるはや

#102 [fix]イベント一覧画面でスコープを使って検索するように変更
  yeahcheese/app/Event.php
  yeahcheese/app/Http/Controllers/EventController.php
  yeahcheese/resources/views/events_list.blade.php
Labels: なるはや

#107 [イベント編集-機能(API)]イベント取得(GET)
  yeahcheese/app/Event.php
  yeahcheese/app/Http/Controllers/Api/EventController.php
  yeahcheese/app/Http/Resources/EventResources.php
  yeahcheese/app/Http/Resources/Picture.php
  yeahcheese/routes/api.php
Labels: なるはや

#110 APIでPictureの全取得機能
  yeahcheese/app/Http/Controllers/Api/PictureController.php
  yeahcheese/app/Http/Resources/PictureResources.php
  yeahcheese/routes/api.php
  yeahcheese/tests/Feature/Api/PictureControllerTest.php
Labels: なるはや

#113 fetchAPIのテストを作成
  yeahcheese/tests/Feature/Api/EventControllerTest.php
Labels: レビュー中

#117 APIのdestroyメソッドとテストの作成
  yeahcheese/app/Http/Controllers/Api/PictureController.php
  yeahcheese/routes/api.php
  yeahcheese/tests/Feature/Api/PictureControllerTest.php
Labels: レビュー中

#116 イベント表示ページに複数の改修
  yeahcheese/app/Event.php
  yeahcheese/app/Http/Controllers/EventController.php
  yeahcheese/resources/views/event.blade.php
  yeahcheese/resources/views/search.blade.php
  yeahcheese/routes/web.php
Labels: レビュー中

#123 [イベント編集-テスト]Seederでファクトリーモデルを利用
  yeahcheese/config/app.php
  yeahcheese/database/seeds/DatabaseSeeder.php
  yeahcheese/database/seeds/EventsTableSeeder.php
  yeahcheese/database/seeds/PicturesTableSeeder.php
  yeahcheese/database/seeds/UsersTableSeeder.php
Labels: なるはや, レビュー中

#121 [refactor-イベント編集]PictureControllerTestにSetUpを作る
  yeahcheese/tests/Feature/Api/EventControllerTest.php
  yeahcheese/tests/Feature/Api/PictureControllerTest.php
Labels: なるはや, レビュー中

#127 [イベント一覧-機能]写真のサムネイルを表示
  yeahcheese/resources/views/events_list.blade.php
  yeahcheese/resources/views/layouts/template.blade.php
Labels: レビュー中

#130 イベントが見つからず検索画面にリダイレクトする際にエラーメッセージを表示する
  yeahcheese/app/Http/Controllers/EventController.php
  yeahcheese/resources/views/search.blade.php
Labels: レビュー中

#129 画像追加APIとテストの作成
  yeahcheese/app/Http/Controllers/Api/PictureController.php
  yeahcheese/app/Picture.php
  yeahcheese/config/filesystems.php
  yeahcheese/tests/Feature/Api/PictureControllerTest.php
Labels: なるはや, レビュー中

#141 イベント編集画面でAPIから表示するデータを取得して表示する機能を追加
  yeahcheese/.gitignore
  yeahcheese/app/Http/Controllers/Api/EventController.php
  yeahcheese/app/Http/Controllers/EventController.php
  yeahcheese/public/mix-manifest.json
  yeahcheese/resources/js/api.js
  yeahcheese/resources/js/index.js
  yeahcheese/resources/views/event_update.blade.php
  yeahcheese/resources/views/events_list.blade.php
  yeahcheese/routes/api.php
  yeahcheese/routes/web.php
  yeahcheese/tests/Feature/Api/EventControllerTest.php
  yeahcheese/webpack.mix.js
Labels: なるはや, レビュー中

#150 イベント一覧、イベント表示、イベント検索、テンプレートのviewを修正
  yeahcheese/resources/views/event.blade.php
  yeahcheese/resources/views/events_list.blade.php
  yeahcheese/resources/views/layouts/template.blade.php
  yeahcheese/resources/views/search.blade.php
Labels: レビュー中

#153 storeAPIに画像バリデーションを追加
  yeahcheese/app/Http/Controllers/Api/PictureController.php
  yeahcheese/app/Picture.php
  yeahcheese/tests/Feature/Api/PictureControllerTest.php
Labels: レビュー中

#165 画像アップロードリクエストの作成
  yeahcheese/resources/js/api.js
  yeahcheese/resources/js/index.js
Labels: レビュー中

#171 イベント更新画面で使用しているVueを単一コンポーネントファイルに変更
  yeahcheese/resources/js/api.js
  yeahcheese/resources/js/app.js
  yeahcheese/resources/js/components/EventEditorComponent.vue
  yeahcheese/resources/js/components/PictureComponent.vue
  yeahcheese/resources/js/components/PictureItemComponent.vue
  yeahcheese/resources/js/index.js
  yeahcheese/resources/views/event_update.blade.php
  yeahcheese/webpack.mix.js
Labels: なるはや

#184 見た目修正
  yeahcheese/config/app.php
  yeahcheese/public/css/style.css
  yeahcheese/resources/lang/ja.json
  yeahcheese/resources/lang/ja/auth.php
  yeahcheese/resources/lang/ja/pagination.php
  yeahcheese/resources/lang/ja/passwords.php
  yeahcheese/resources/lang/ja/validation.php
  yeahcheese/resources/views/auth/login.blade.php
  yeahcheese/resources/views/auth/register.blade.php
  yeahcheese/resources/views/event_create.blade.php
  yeahcheese/resources/views/event_show.blade.php
  yeahcheese/resources/views/events_list.blade.php
  yeahcheese/resources/views/layouts/template.blade.php
  yeahcheese/resources/views/search.blade.php
Labels: レビュー中

#195 イベント編集画面のみため変更
  yeahcheese/resources/js/components/EventEditorComponent.vue
  yeahcheese/resources/js/components/PictureComponent.vue
  yeahcheese/resources/js/components/PictureItemComponent.vue
  yeahcheese/resources/views/event_update.blade.php
Labels: なるはや, レビュー中

#203 イベント編集画面で使用しているVueコンポーネントの修正とリファクタ
  yeahcheese/resources/js/components/EventEditorComponent.vue
  yeahcheese/resources/js/components/PictureComponent.vue
Labels: レビュー中

#216 チェックボックスのデザインをレスポンシブ対応に変更
  yeahcheese/resources/views/events_list.blade.php
Labels: レビュー中

#213 イベントの作成者かどうかを判定するメソッドを追加する
  yeahcheese/app/Event.php
  yeahcheese/app/Http/Controllers/EventController.php
Labels: レビュー中

#215 不正な値のまま何度も更新ボタンを押すと同一内容のエラーメッセージが増えるバグを修正
  yeahcheese/resources/js/components/EventEditorComponent.vue
Labels: レビュー中

#218 イベント編集画面で日付を正しい公開範囲に変更しても更新できない不具合が発生していたのを修正
  yeahcheese/resources/js/components/EventEditorComponent.vue
Labels: なるはや
